name: github pages

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6.0.2

            - name: setup pnpm
              uses: pnpm/action-setup@v5.0.0

            - name: setup node
              uses: actions/setup-node@v6.4.0
              with:
                  node-version: '24.x'
                  cache: 'pnpm'

            - name: install
              run: pnpm install --frozen-lockfile

            - name: build
              run: pnpm build

            - name: add nojekyll
              run: touch ./out/.nojekyll

            - name: deploy
              uses: peaceiris/actions-gh-pages@v4.0.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
